module.exports = {
  mobile_carriers: [
    { name: "Alltel", email: "sms.alltelwireless.com", id: 100 },
    { name: "AT&T", email: "mms.att.net", id: 101 },
    { name: "Bell Mobility", email: "txt.bellmobility.ca", id: 102 },
    { name: "Boost Mobile", email: "sms.myboostmobile.com", id: 103 },
    { name: "Cricket", email: "mms.cricketwireless.net", id: 104 },
    { name: "Sprint", email: "messaging.sprintpcs.com", id: 105 },
    { name: "T-Mobile", email: "tmomail.net", id: 106 },
    { name: "Telus", email: "msg.telus.com", id: 107 },
    { name: "US Cellular", email: "email.uscc.net", id: 108 },
    { name: "Verizon", email: "vtext.com", id: 109 },
    { name: "Virgin Mobile (US)", email: "vmobl.com", id: 110 },
    { name: "AIO Wireless", email: "aiowireless.net", id: 111 },
    { name: "Alaska Communications", email: "msg.acsalaska.com", id: 112 },
    { name: "Alaska Digitel", email: "akdigitel.com", id: 113 },
    { name: "Appalachian Wireless", email: "awsms.com", id: 114 },
    { name: "Arch Wireless", email: "archwireless.net", id: 115 },
    { name: "Assurance Wireless", email: "vmobl.com", id: 116 },
    { name: "Bluegrass Cellular", email: "sms.bluecell.com", id: 117 },
    {
      name: "C Beyond (All Page Wireless)",
      email: "cbeyond.sprintpcs.com",
      id: 118,
    },
    { name: "C Spire", email: "cspire1.com", id: 119 },
    { name: "C Spire (Cellular South)", email: "csouth1.com", id: 120 },
    { name: "Cellcom", email: "cellcom.quiktxt.com", id: 121 },
    { name: "Cellular One", email: "mobile.celloneusa.com", id: 122 },
    { name: "Cellular One Nation", email: "sms.cellonenation.net", id: 123 },
    { name: "Centurytel", email: "messaging.centurytel.net", id: 124 },
    { name: "Chat Mobility", email: "mail.msgsender.com", id: 125 },
    { name: "Chatr Mobile", email: "pcs.rogers.com", id: 126 },
    { name: "Cingular", email: "cingularme.com", id: 127 },
    { name: "Cleartalk", email: "sms.cleartalk.us", id: 128 },
    { name: "Comcast PCS", email: "comcastpcs.textmsg.com", id: 129 },
    { name: "Consumer Cellular", email: "txt.att.net", id: 130 },
    { name: "Corr Wireless", email: "corrwireless.net", id: 131 },
    { name: "Credo", email: "messaging.sprintpcs.com", id: 132 },
    { name: "Fido", email: "fido.ca", id: 133 },
    { name: "General Communications Inc.", email: "mobile.gci.net", id: 134 },
    { name: "GoPhone", email: "vtext.com", id: 135 },
    { name: "H2O", email: "txt.att.net", id: 136 },
    { name: "iWireless", email: "iwspcs.net", id: 137 },
    { name: "Inland Cellular", email: "inlandlink.com", id: 138 },
    { name: "Koodo Mobile", email: "msg.telus.com", id: 139 },
    { name: "Lyca", email: "lycamobile.com", id: 140 },
    { name: "M1 Wireless", email: "m1.com.sg", id: 141 },
    { name: "Manitoba Telecom Services", email: "text.mts.net", id: 142 },
    { name: "Mosaic Telecom", email: "sms.chibardun.net", id: 143 },
    { name: "Nemont", email: "sms.nemont.mobi", id: 144 },
    { name: "Nex-Tech Wireless", email: "sms.ntwls.net", id: 145 },
    { name: "Nextel", email: "messaging.nextel.com", id: 146 },
    { name: "nTelos Wireless", email: "pcs.ntelos.com", id: 147 },
    { name: "Optus", email: "optusmobile.com.au", id: 148 },
    { name: "Pocket", email: "sms.pocket.com", id: 149 },
    { name: "Qwest", email: "qwestmp.com", id: 150 },
    { name: "Republic Wireless", email: "text.republicwireless.com", id: 151 },
    { name: "Sasktel", email: "sms.sasktel.com", id: 152 },
    { name: "Simple Mobile", email: "smtext.com", id: 153 },
    { name: "Solo Bell", email: "txt.bell.ca", id: 154 },
    { name: "Solo Mobile", email: "txt.bellmobility.ca", id: 155 },
    { name: "Southern Link Wireless", email: "page.southernlinc.com", id: 156 },
    { name: "Straight Talk - AT&T", email: "txt.att.net", id: 157 },
    {
      name: "Straight Talk - Sprint PCS",
      email: "messaging.sprintpcs.com",
      id: 158,
    },
    { name: "Straight Talk - T-Mobile", email: "tmomail.net", id: 159 },
    { name: "Straight Talk - Tracfone", email: "mmst5.tracfone.com", id: 160 },
    { name: "Straight Talk - Verizon", email: "vtext.com", id: 161 },
    { name: "Telstra", email: "onlinesms.telstra.com", id: 162 },
    { name: "TextNow.me", email: "textnow.me", id: 163 },
    { name: "Ting(CDMA)", email: "message.ting.com", id: 164 },
    { name: "Verizon Alt.", email: "vzwpix.com", id: 165 },
    { name: "Viaero Wireless", email: "viaerosms.com", id: 166 },
    { name: "Virgin Mobile (Canada)", email: "vmobile.ca", id: 167 },
    { name: "VoiceStream Wireless", email: "voicestream.net", id: 168 },
    { name: "Westlink", email: "westlink.com", id: 169 },
    { name: "Freedom Mobile", email: "txt.freedommobile.ca", id: 170 },
    { name: "Cellular One Illinois", email: "sms.cellular1.net", id: 171 },
    { name: "Rogers Wireless", email: "pcs.rogers.com", id: 172 },
    { name: "MetroPCS", email: "mymetropcs.com", id: 173 },
    { name: "Centennial", email: "cwemail.com", id: 174 },
    { name: "Cellular South", email: "csouth1.com", id: 175 },
    { name: "Cincinnati Bell", email: "gocbw.com", id: 176 },
    { name: "Google Project Fi", email: "msg.fi.google.com", id: 177 },
    { name: "Net10 Wireless", email: "mms.att.net", id: 178 },
    { name: "Carolina West Wireless", email: "cwwsms.com", id: 179 },
    { name: "PC Telecom", email: "mobiletxt.ca", id: 180 },
    { name: "Xfinity Mobile", email: "vtext.com", id: 181 },
    { name: "Spectrum Mobile", email: "nexmo.com", id: 182 },
    { name: "Ting(GSM)", email: "tmomail.net", id: 183 },
    { name: "Family Mobile", email: "tmomail.net", id: 184 },
    { name: "Total Wireless", email: "vtext.com", id: 185 },
  ],
};
